# Events kreves i konfigurering av en nginx.conf-fil. Den kan stå tom
events {
}

# Vi har en HTTP-blokk for å kunne konfiguere HTTP-trafikk
http {
    # Her defineres en virtuell server som kreves for proxy
    server {
        # Vi lytter til port 80, standard port for HTTP og vi kan bruke localhost inne i container
        listen 80;
        server_name localhost;
        
        # Proxy for API-et vårt. Url som ender på /api/ konfigurerer vi her
        location / {
            # Her setter vi hvor vi videresender besøkende på dette url-et. Vi må sette url-en som tilhører backenden 
            # inne i containern vår
            proxy_pass http://product-api:8080;
        } 
    }      
}  